Uniqlo/Uniqlo/ViewComponents/LayoutHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Uniqlo.DataAccess;
using Uniqlo.Helpers;
using Uniqlo.ViewModels.Baskets;

namespace Uniqlo.ViewComponents;

public class LayoutHeaderViewComponent(UniqloDbContext _context):ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var basket = BasketHelper.GetBasket(HttpContext.Request);
        var basketItems = await _context.Products
            .Where(x => basket.Select(y => y.Id)
            .Contains(x.Id))
            .Select(x=> new BasketItemVM()
            {
                Id = x.Id,
                Name = x.Name,
                ImageUrl = x.CoverImage,
                SellPrice = x.SellPrice,
                Discount = x.Discount
            })
            .ToListAsync();
        
        foreach (var item in basketItems)
            item.Count = basket.First(x => x.Id == item.Id).Count;
        return View(basketItems);
    }
} 

Uniqlo/Uniqlo/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- Bootstrap Fremwork Main Css -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- All Plugins css -->
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <!-- Theme shortcodes/elements style -->  
    <link rel="stylesheet" href="~/assets/css/shortcode/shortcodes.css">
    <!-- Theme main style -->
    <link rel="stylesheet" href="~/assets/style.css">
    <!-- Responsive css -->
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <!-- User style -->
    <link rel="stylesheet" href="~/assets/css/custom.css">

    <!-- Modernizr JS -->
    <script src="~/assets/js/vendor/modernizr-3.11.2.min.js"></script>
    @await RenderSectionAsync("style",false)
    @await RenderSectionAsync("scripts",false)
</head>

<body>
@await Component.InvokeAsync("LayoutHeader")
@* <vc:layout-header></vc:layout-header> *@
@RenderBody()
<!-- Start Footer Area -->
<footer class="htc__foooter__area bg__cat--2 footer--4">
    <div class="container-fluid">
        <div class="footer__container clearfix">
            <div class="row">
                <!-- Start Single Footer Widget -->
                <div class="col-md-6 col-lg-3 col-sm-6">
                    <div class="ft__widget">
                        <div class="ft__logo">
                            <a asp-action="Index" asp-controller="Home">
                                <img src="~/assets/images/logo/uniqlo.png" alt="footer logo">
                            </a>
                        </div>
                        <div class="footer__details">
                            <p>Get 10% discount with notified about the latest news and updates.</p>
                        </div>
                    </div>
                </div>
                <!-- End Single Footer Widget -->
                <!-- Start Single Footer Widget -->
                <div class="col-md-6 col-lg-3 offset-lg-1 col-sm-6 smb-30 xmt-30">
                    <div class="ft__widget">
                        <h2 class="ft__title">Newsletter</h2>
                        <div class="newsletter__form">
                            <div class="input__box">
                                <div id="mc_embed_signup">
                                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                                        <div id="mc_embed_signup_scroll" class="htc__news__inner">
                                            <div class="news__input">
                                                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" required>
                                            </div>
                                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                                            <div class="clearfix subscribe__btn"><input type="submit" value="Send" name="subscribe" id="mc-embedded-subscribe" class="bst__btn btn--white__color">

                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Single Footer Widget -->
                <!-- Start Single Footer Widget -->
                <div class="col-md-6 col-lg-3 col-sm-6 smt-30 xmt-30">
                    <div class="ft__widget contact__us">
                        <h2 class="ft__title">Contact Us</h2>
                        <div class="footer__inner">
                            <p> 319 Clematis St. <br> Suite 100 WPB, FL 33401 </p>
                        </div>
                    </div>
                </div>
                <!-- End Single Footer Widget -->
                <!-- Start Single Footer Widget -->
                <div class="col-md-6 col-lg-2  col-sm-6 smt-30 xmt-30">
                    <div class="ft__widget">
                        <h2 class="ft__title">Follow Us</h2>
                        <ul class="social__icon">
                            <li><a href="https://twitter.com/devitemsllc" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
                            <li><a href="https://www.instagram.com/devitems/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://plus.google.com/" target="_blank"><i class="zmdi zmdi-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
                <!-- End Single Footer Widget -->
            </div>
        </div>
        <!-- Start Copyright Area -->
        <div class="htc__copyright__area">
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <div class="copyright__inner">
                        <div class="copyright">
                            <p>© 2022 Uniqlo. Made with <i class="ti-heart"></i> by <a target="_blank" href="https://www.hasthemes.com">HasThemes.</a></p>
                        </div>
                        <ul class="footer__menu">
                            <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                            <li><a href="shop.html">Product</a></li>
                            <li><a asp-action="Contact" asp-controller="Home">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Copyright Area -->
    </div>
</footer>
<!-- End Footer Area -->
<!-- Body main wrapper end -->
<!-- QUICKVIEW PRODUCT -->
<div id="quickview-wrapper">
    <!-- Modal -->
    <div class="modal fade" id="productModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal__container" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="modal-product">
                        <!-- Start product images -->
                        <div class="product-images">
                            <div class="main-image images">
                                <img alt="big images" src="~/assets/images/product/big-img/1.jpg">
                            </div>
                        </div>
                        <!-- end product images -->
                        <div class="product-info">
                            <h1>Simple Fabric Bags</h1>
                            <div class="rating__and__review">
                                <ul class="rating">
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                </ul>
                                <div class="review">
                                    <a href="#">4 customer reviews</a>
                                </div>
                            </div>
                            <div class="price-box-3">
                                <div class="s-price-box">
                                    <span class="new-price">$17.20</span>
                                    <span class="old-price">$45.00</span>
                                </div>
                            </div>
                            <div class="quick-desc">
                                Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern look.
                            </div>
                            <div class="select__color">
                                <h2>Select color</h2>
                                <ul class="color__list">
                                    <li class="red"><a title="Red" href="#">Red</a></li>
                                    <li class="gold"><a title="Gold" href="#">Gold</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                </ul>
                            </div>
                            <div class="select__size">
                                <h2>Select size</h2>
                                <ul class="color__list">
                                    <li class="l__size"><a title="L" href="#">L</a></li>
                                    <li class="m__size"><a title="M" href="#">M</a></li>
                                    <li class="s__size"><a title="S" href="#">S</a></li>
                                    <li class="xl__size"><a title="XL" href="#">XL</a></li>
                                    <li class="xxl__size"><a title="XXL" href="#">XXL</a></li>
                                </ul>
                            </div>
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Share this product</h3>
                                    <ul class="social-icons">
                                        <li><a target="_blank" title="rss" href="#" class="rss social-icon"><i class="zmdi zmdi-rss"></i></a></li>
                                        <li><a target="_blank" title="Linkedin" href="#" class="linkedin social-icon"><i class="zmdi zmdi-linkedin"></i></a></li>
                                        <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="zmdi zmdi-pinterest"></i></a></li>
                                        <li><a target="_blank" title="Tumblr" href="#" class="tumblr social-icon"><i class="zmdi zmdi-tumblr"></i></a></li>
                                        <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="addtocart-btn">
                                <a href="#">Add to cart</a>
                            </div>
                        </div><!-- .product-info -->
                    </div><!-- .modal-product -->
                </div><!-- .modal-body -->
            </div><!-- .modal-content -->
        </div><!-- .modal-dialog -->
    </div>
    <!-- END Modal -->
</div>
<!-- END QUICKVIEW PRODUCT -->
<!-- Placed js at the end of the document so the pages load faster -->

<!-- jquery latest version -->
<script src="~/assets/js/vendor/jquery-3.6.0.min.js"></script>
<script src="~/assets/js/vendor/jquery-migrate-3.3.2.min.js"></script>
<script src="~/assets/js/vendor/jquery.waypoints.js"></script>
<!-- Bootstrap Framework js -->
<script src="~/assets/js/bootstrap.bundle.min.js"></script>
<!-- All js plugins included in this file. -->
<script src="~/assets/js/plugins.js"></script>
<!-- Main js file that contents all jQuery plugins activation. -->
<script src="~/assets/js/main.js"></script>

</body>

</html>